import { Fragment } from 'react';
import Head from 'next/head';
import Image from 'next/image';

import image1 from '../public/images/aboutUs/img1.png';
import image2 from '../public/images/aboutUs/img2.png';
import team1 from '../public/images/aboutUs/team1.png';
import team2 from '../public/images/aboutUs/team2.png';
import team3 from '../public/images/aboutUs/team3.png';
import team4 from '../public/images/aboutUs/team4.png';

function AboutUs() {
  return (
    <Fragment>
      <Head>
        <title>About Us - Stratuscoder Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-about-us-section-1 bg-cover bg-center">
        <div className="container mx-auto pt-36 pb-44">
          <div className="max-w-4xl sm:px-6">
            <p className="font-semibold uppercase pb-5 sm:text-[14px]">about us</p>
            <h1 className="text-6xl leading-tight font-bold mb-11 sm:text-5xl">
              We help business grow. <span className="text-active">Together</span>
            </h1>
            <button
              type="button"
              className="uppercase text-lg font-semibold px-14 py-3 bg-button shadow-button rounded-full">Get in touch</button>
          </div>
        </div>
      </section>
      <section className="bg-white">
        <div className="container mx-auto py-32 sm:py-20 sm:pb-0">
          <div className="flex justify-between sm:flex-wrap">
            <div className="basis-5/12 sm:basis-full sm:p-6">
              <h2 className="text-5xl leading-tight font-semibold mb-4 sm:text-4xl">Who <span className="text-active">We</span> Are</h2>
              <p className="text-muted font-normal">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
            </div>
            <div className="basis-1/2 sm:basis-full">
              <Image src={image1} alt="Image1" className="w-full" />
            </div>
          </div>
          <div className="flex -mt-24 sm:mt-0 mb-32 sm:mb-20">
            <div className="basis-2/3 sm:basis-full flex bg-home-section-4-bottom py-10 sm:py-0 sm:flex-wrap sm:px-6">
              <div className="basis-1/3 sm:basis-1/2 px-8 my-8 sm:p-0 sm:pb-4 text-center border-home-section-4-bottom-border border-r sm:border-r-2 sm:border-b-2">
                <h1 className="text-6xl font-extrabold mb-5 sm:text-4xl">1830+</h1>
                <p className="font-bold">Project executed</p>
              </div>
              <div className="basis-1/3  sm:basis-1/2 px-8 my-8 sm:p-0 sm:pb-4 text-center border-home-section-4-bottom-border border-r sm:border-r-0 sm:border-b-2">
                <h1 className="text-6xl font-extrabold mb-5 sm:text-4xl">220</h1>
                <p className="font-bold">Data analytics</p>
              </div>
              <div className="basis-1/3 sm:basis-full px-8 my-8 sm:mt-0 sm:p-0 text-center">
                <h1 className="text-6xl font-extrabold mb-5 sm:text-4xl">834+</h1>
                <p className="font-bold">Satisfied customers</p>
              </div>
            </div>
          </div>
          <div className="flex justify-between flex-wrap">
            <div className="basis-1/2 sm:order-2 sm:basis-full">
              <Image src={image2} alt="Image2" className="w-full" />
            </div>
            <div className="basis-5/12 sm:basis-full sm:px-6">
              <h2 className="text-5xl leading-tight font-semibold mb-4 sm:text-4xl">Benefits of choosing <span className="text-active">Stratuscoder</span></h2>
              <p className="text-muted font-normal">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
              <div className="mt-11">
                <h6 className="text-2xl font-semibold mb-4 sm:text-xl">Locally recommended</h6>
                <div className="bg-progress h-6 mb-8 flex">
                  <div className="bg-button font-semibold pr-4 flex items-center justify-end" style={{ width: '80%' }}>80%</div>
                </div>
                <h6 className="text-2xl font-semibold mb-4 sm:text-xl">Project comleted successflly</h6>
                <div className="bg-progress h-6 mb-8 flex">
                  <div className="bg-button font-semibold pr-4 flex items-center justify-end" style={{ width: '90%' }}>90%</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-about-us-section-3 bg-cover bg-center">
        <div className="container mx-auto py-32 sm:px-6 sm:py-20">
          <h2 className="text-5xl leading-tight font-semibold text-center mb-4">How We <span className="text-active">Work</span></h2>
          <p className="text-muted text-2xl font-normal text-center">Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
          <div className="mt-11">
            <div className="flex flex-row flex-wrap">
              <div className="basis-1/3 sm:basis-full px-8 sm:mb-6 py-10 bg-card-2 bg-about-us-card backdrop-blur-lg border-r border-card-divider hover:bg-about-us-card-hover hover:shadow-home-section-3-card cursor-default relative">
                <div className="w-20 h-20 mb-8 bg-active rounded-full flex items-center justify-center">
                  <svg width="42" height="42" viewBox="0 0 42 42" fill="none" xmlns="http://www.w3.org/2000/svg" className="fill-white">
                    <path d="M30.532 19.9071C30.532 14.6571 26.2484 10.3735 20.9984 10.3735C15.7484 10.3735 11.4648 14.6571 11.4648 19.9071C11.4648 20.6635 11.5485 21.4198 11.7585 22.1744C12.0112 23.3918 12.4722 24.1481 13.1022 25.1981C13.2285 25.4508 13.3959 25.7018 13.5649 25.9954C13.7749 26.3318 13.9422 26.6681 14.1522 26.9618C14.9922 28.3481 15.4958 29.1454 15.4958 30.7844V34.7318C15.4958 35.7391 16.2095 36.5381 17.1758 36.7054C17.5958 38.8481 18.8558 40.1918 20.9985 40.1918C23.1412 40.1918 24.4422 38.8481 24.8212 36.7054C25.7875 36.5381 26.5012 35.6981 26.5012 34.7318V30.7844C26.5012 29.1471 27.0049 28.3071 27.8449 26.9618C28.0122 26.6681 28.2222 26.3318 28.4322 25.9954C28.5995 25.7018 28.7685 25.4491 28.8949 25.1981C29.5249 24.1481 29.9875 23.3918 30.2385 22.1744C30.4485 21.4197 30.5322 20.6634 30.5322 19.9071H30.532ZM24.862 31.7935H17.2184V30.8272C17.2184 30.6172 17.2184 30.4499 17.1758 30.2809H24.8622C24.8622 30.4482 24.8195 30.6172 24.8195 30.8272L24.8212 31.7935H24.862ZM24.4847 35.1125H17.5118C17.3018 35.1125 17.1755 34.9452 17.1755 34.7762V33.4735H24.8191V34.7762C24.8617 34.9435 24.6944 35.1125 24.4844 35.1125H24.4847ZM20.9983 38.5562C20.5357 38.5562 19.361 38.5562 18.8983 36.7925H23.1412C22.6785 38.5562 21.4612 38.5562 20.9985 38.5562H20.9983ZM28.6012 21.8397C28.3912 22.7634 28.0548 23.3934 27.4675 24.3597C27.3002 24.6124 27.1738 24.8634 27.0048 25.1571C26.7948 25.4934 26.6275 25.8297 26.4585 26.0807C25.9548 26.9207 25.4922 27.6771 25.1985 28.5581H16.8821C16.5884 27.6754 16.1684 26.9207 15.6221 26.0807C15.4547 25.7871 15.2447 25.4934 15.0757 25.1571C14.9084 24.8634 14.7394 24.5697 14.6131 24.3597C14.0257 23.3524 13.6894 22.7634 13.4794 21.7971C13.3121 21.1671 13.2267 20.5371 13.2267 19.9071C13.2267 15.5807 16.7541 12.0535 21.0803 12.0535C25.4067 12.0535 28.9339 15.5808 28.9339 19.9071C28.8519 20.5371 28.7682 21.1671 28.6009 21.8397H28.6012Z" />
                    <path d="M38.3029 19.0671H34.8166C34.3539 19.0671 33.9766 19.4445 33.9766 19.9071C33.9766 20.3698 34.3539 20.7471 34.8166 20.7471H38.3029C38.7656 20.7471 39.1429 20.3698 39.1429 19.9071C39.1429 19.4461 38.7656 19.0671 38.3029 19.0671Z" />
                    <path d="M30.7436 11.0038C30.9536 11.0038 31.1636 10.9201 31.3309 10.7511L33.8082 8.2738C34.1446 7.93747 34.1446 7.4338 33.8082 7.09746C33.4719 6.76113 32.9683 6.76113 32.6319 7.09746L30.1546 9.57479C29.8183 9.91112 29.8183 10.4148 30.1546 10.7511C30.3236 10.9201 30.5336 11.0038 30.7436 11.0038H30.7436Z" />
                    <path d="M21.0002 6.93001C21.4628 6.93001 21.8402 6.55266 21.8402 6.09001V2.60367C21.8402 2.141 21.4628 1.76367 21.0002 1.76367C20.5375 1.76367 20.1602 2.14102 20.1602 2.60367V6.09001C20.1602 6.55268 20.5375 6.93001 21.0002 6.93001Z" />
                    <path d="M10.6668 10.7531C10.8341 10.9204 11.0441 11.0057 11.2541 11.0057C11.4641 11.0057 11.6741 10.9221 11.8415 10.7531C12.1778 10.4167 12.1778 9.91308 11.8415 9.57674L9.36413 7.09941C9.0278 6.76309 8.52413 6.76309 8.18779 7.09941C7.85146 7.43574 7.85146 7.93941 8.18779 8.27575L10.6668 10.7531Z" />
                    <path d="M7.22282 19.0671H3.73648C3.27381 19.0671 2.89648 19.4445 2.89648 19.9071C2.89648 20.3698 3.27383 20.7471 3.73648 20.7471H7.22282C7.68549 20.7471 8.06282 20.3698 8.06282 19.9071C8.06282 19.4461 7.68547 19.0671 7.22282 19.0671Z" />
                    <path d="M10.6671 29.0638L8.18975 31.5411C7.85342 31.8774 7.85342 32.3811 8.18975 32.7174C8.35709 32.8848 8.56709 32.9701 8.77707 32.9701C8.98706 32.9701 9.19707 32.8864 9.3644 32.7174L11.8417 30.2401C12.1781 29.9038 12.1781 29.4001 11.8417 29.0638C11.507 28.7274 10.9623 28.7274 10.667 29.0638H10.6671Z" />
                    <path d="M31.3329 29.0638C30.9966 28.7274 30.4929 28.7274 30.1565 29.0638C29.8202 29.4001 29.8202 29.9038 30.1565 30.2401L32.6339 32.7174C32.8012 32.8848 33.0112 32.9701 33.2212 32.9701C33.4312 32.9701 33.6412 32.8864 33.8085 32.7174C34.1449 32.3811 34.1449 31.8774 33.8085 31.5411L31.3329 29.0638Z" />
                  </svg>
                </div>
                <h5 className="text-2xl font-semibold mb-4">Data exploration and proof of concept</h5>
                <p className="text-muted font-normal">Enterprise solutions with Java 17 and more. With lambda, functional programming and streams, Java is still a favorite choice as enterprise application technology</p>
                <Image src="/images/aboutUs/number1.png" alt="1" width="113" height="210" className="absolute top-10 right-10" />
              </div>
              <div className="basis-1/3 sm:basis-full sm:mb-6 px-8 py-10 bg-about-us-card backdrop-blur-lg border-x border-card-divider hover:bg-about-us-card-hover hover:shadow-home-section-3-card cursor-default relative">
                <div className="w-20 h-20 mb-8 bg-active rounded-full flex items-center justify-center">
                  <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg" className="fill-white">
                    <path d="M20.5007 19.5C20.4097 19.5 20.3203 19.4845 20.2339 19.4522L5.58811 14.0563C5.2844 13.9453 5.08398 13.6555 5.08398 13.3333C5.08398 13.0111 5.28594 12.7212 5.58965 12.6102L15.6105 8.92567C16.0082 8.78075 16.4538 8.98425 16.6002 9.38354C16.7467 9.78283 16.5417 10.2253 16.1424 10.3733L8.08715 13.3333L20.5007 17.9074L32.9142 13.3333L24.8589 10.3717C24.4597 10.2253 24.2546 9.78129 24.4011 9.382C24.5475 8.98271 24.9915 8.77921 25.3908 8.92412L35.4117 12.6087C35.7154 12.7212 35.9173 13.0111 35.9173 13.3333C35.9173 13.6555 35.7169 13.9453 35.4132 14.0563L20.7674 19.4522C20.681 19.4845 20.5916 19.5 20.5007 19.5Z" />
                    <path d="M20.4996 37.9998C20.4086 37.9998 20.3192 37.9844 20.2344 37.952L12.0481 34.9457C11.6489 34.7993 11.4438 34.3568 11.5903 33.956C11.7367 33.5567 12.1807 33.3517 12.58 33.4981L20.4996 36.4072L28.4206 33.4981C28.8199 33.3501 29.2624 33.5567 29.4104 33.956C29.5569 34.3553 29.3518 34.7977 28.9525 34.9457L20.7663 37.952C20.6799 37.9844 20.5905 37.9998 20.4996 37.9998Z" />
                    <path d="M5.85482 28.38C5.42932 28.38 5.08398 28.0347 5.08398 27.6092V13.3333C5.08398 12.9078 5.42932 12.5625 5.85482 12.5625C6.28032 12.5625 6.62565 12.9078 6.62565 13.3333V27.6092C6.62565 28.0347 6.28032 28.38 5.85482 28.38Z" />
                    <path d="M35.1458 28.38C34.7203 28.38 34.375 28.0347 34.375 27.6092V13.3333C34.375 12.9078 34.7203 12.5625 35.1458 12.5625C35.5713 12.5625 35.9167 12.9078 35.9167 13.3333V27.6092C35.9167 28.0347 35.5713 28.38 35.1458 28.38Z" />
                    <path d="M20.4993 13.3333C20.0738 13.3333 19.7285 12.988 19.7285 12.5625V6.39583C19.7285 5.97033 20.0738 5.625 20.4993 5.625C20.9248 5.625 21.2702 5.97033 21.2702 6.39583V12.5625C21.2702 12.988 20.9248 13.3333 20.4993 13.3333Z" />
                    <path d="M34.2829 34.0536C34.0856 34.0536 33.8882 33.9781 33.7371 33.8286L29.9755 30.0669C29.6748 29.7663 29.6748 29.2776 29.9755 28.9769C30.2761 28.6763 30.7648 28.6763 31.0654 28.9769L34.8271 32.7386C35.1277 33.0392 35.1277 33.5279 34.8271 33.8286C34.6776 33.9781 34.4802 34.0536 34.2829 34.0536Z" />
                    <path d="M6.71653 34.0536C6.5192 34.0536 6.32186 33.9781 6.17078 33.8286C5.87016 33.5279 5.87016 33.0392 6.17078 32.7386L9.93245 28.9769C10.2331 28.6763 10.7218 28.6763 11.0224 28.9769C11.323 29.2776 11.323 29.7663 11.0224 30.0669L7.26074 33.8286C7.1112 33.9781 6.91386 34.0536 6.71653 34.0536Z" />
                    <path d="M20.4993 38.0002C20.0738 38.0002 19.7285 37.6548 19.7285 37.2293V18.7293C19.7285 18.3038 20.0738 17.9585 20.4993 17.9585C20.9248 17.9585 21.2702 18.3038 21.2702 18.7293V37.2293C21.2702 37.6548 20.9248 38.0002 20.4993 38.0002Z" />
                    <path d="M20.4993 7.16667C18.7989 7.16667 17.416 5.78379 17.416 4.08333C17.416 2.38287 18.7989 1 20.4993 1C22.1998 1 23.5827 2.38287 23.5827 4.08333C23.5827 5.78379 22.1998 7.16667 20.4993 7.16667ZM20.4993 2.54167C19.6499 2.54167 18.9577 3.23388 18.9577 4.08333C18.9577 4.93279 19.6499 5.625 20.4993 5.625C21.3488 5.625 22.041 4.93279 22.041 4.08333C22.041 3.23388 21.3488 2.54167 20.4993 2.54167Z" />
                    <path d="M35.9173 38.0002C34.2169 38.0002 32.834 36.6173 32.834 34.9168C32.834 33.2164 34.2169 31.8335 35.9173 31.8335C37.6178 31.8335 39.0007 33.2164 39.0007 34.9168C39.0007 36.6173 37.6178 38.0002 35.9173 38.0002ZM35.9173 33.3752C35.0679 33.3752 34.3757 34.0674 34.3757 34.9168C34.3757 35.7663 35.0679 36.4585 35.9173 36.4585C36.7668 36.4585 37.459 35.7663 37.459 34.9168C37.459 34.0674 36.7668 33.3752 35.9173 33.3752Z" />
                    <path d="M5.08333 38.0002C3.38287 38.0002 2 36.6173 2 34.9168C2 33.2164 3.38287 31.8335 5.08333 31.8335C6.78379 31.8335 8.16667 33.2164 8.16667 34.9168C8.16667 36.6173 6.78379 38.0002 5.08333 38.0002ZM5.08333 33.3752C4.23388 33.3752 3.54167 34.0674 3.54167 34.9168C3.54167 35.7663 4.23388 36.4585 5.08333 36.4585C5.93279 36.4585 6.625 35.7663 6.625 34.9168C6.625 34.0674 5.93279 33.3752 5.08333 33.3752Z" />
                  </svg>
                </div>
                <h5 className="text-2xl font-semibold mb-4">Model development</h5>
                <p className="text-muted font-normal">Build highly available and robust APIs with quality. As mirco-services gaining boom, REST APIs are the backbone, let’s do APIs right</p>
                <Image src="/images/aboutUs/number2.png" alt="2" width="150" height="214" className="absolute top-10 right-10" />
              </div>
              <div className="basis-1/3 sm:basis-full sm:mb-6 px-8 py-10 bg-about-us-card backdrop-blur-lg border-l border-card-divider hover:bg-about-us-card-hover hover:shadow-home-section-3-card cursor-default relative">
                <div className="w-20 h-20 mb-8 bg-active rounded-full flex items-center justify-center">
                  <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg" className="fill-white">
                    <path d="M37.333 3.6921C37.3035 3.42463 37.1838 3.17517 36.9937 2.98472C36.8036 2.79427 36.5543 2.67416 36.2869 2.64413H36.2856C33.3735 2.30969 21.0847 1.6235 13.3878 12.1431L7.73277 12.3597C7.53614 12.3669 7.3443 12.4224 7.1742 12.5212C7.00409 12.6201 6.86096 12.7594 6.75743 12.9267L2.92868 19.0962C2.82494 19.2633 2.76384 19.4534 2.75072 19.6497C2.7376 19.8459 2.77288 20.0424 2.85346 20.2219C2.93403 20.4014 3.05743 20.5583 3.21283 20.679C3.36823 20.7996 3.55087 20.8802 3.74472 20.9138L8.84428 21.797C8.73438 22.1848 8.61986 22.5644 8.51889 22.9676C8.46871 23.17 8.4715 23.3819 8.52698 23.5828C8.58246 23.7838 8.68877 23.9671 8.83566 24.1151L15.8627 31.1414C16.0904 31.3679 16.3985 31.4949 16.7196 31.4948C16.8178 31.4949 16.9156 31.4828 17.0108 31.4588C17.4131 31.358 17.7919 31.2438 18.1788 31.1341L19.0646 36.2336C19.0981 36.4275 19.1788 36.6101 19.2994 36.7655C19.42 36.9209 19.577 37.0443 19.7564 37.1249C19.9359 37.2055 20.1324 37.2408 20.3287 37.2276C20.525 37.2145 20.7151 37.1534 20.8822 37.0496L27.051 33.2215C27.2185 33.1182 27.358 32.9752 27.4571 32.8052C27.5562 32.6352 27.6119 32.4434 27.6193 32.2468L27.8393 26.587C38.355 18.8902 37.6674 6.60588 37.333 3.6921ZM4.02858 19.6943L7.78041 13.6085L12.5088 13.4274C11.0993 15.6608 9.98811 18.0689 9.20339 20.5905L4.02858 19.6943ZM16.7465 30.2577L9.7311 23.271C10.0729 21.903 10.4968 20.557 11.0005 19.24L20.7521 28.9917C19.4435 29.4935 18.1059 29.9162 16.7465 30.2577ZM26.3931 32.1589L20.2841 35.9498L19.3852 30.7752C21.9108 29.9894 24.3226 28.8762 26.559 27.4639L26.3931 32.1589ZM22.0137 28.4856L11.5128 17.9848C16.9601 5.43526 27.9543 3.74215 33.4561 3.74215C34.3381 3.73984 35.2195 3.7861 36.0965 3.8807C36.4625 7.14718 37.1969 21.8866 22.0137 28.4856Z" />
                    <path d="M23.5707 10.0404C22.9233 10.6879 22.4824 11.5129 22.3038 12.411C22.1252 13.3091 22.2169 14.2399 22.5673 15.0859C22.9177 15.9319 23.5112 16.6549 24.2725 17.1636C25.0339 17.6723 25.929 17.9439 26.8447 17.9439C27.7603 17.9439 28.6554 17.6723 29.4168 17.1636C30.1782 16.6549 30.7716 15.9319 31.122 15.0859C31.4724 14.2399 31.5641 13.3091 31.3855 12.411C31.2069 11.5129 30.766 10.6879 30.1186 10.0404C29.2496 9.17343 28.0722 8.68652 26.8447 8.68652C25.6171 8.68652 24.4397 9.17343 23.5707 10.0404ZM29.2348 15.7039C28.7621 16.1766 28.1599 16.4986 27.5042 16.629C26.8486 16.7595 26.1689 16.6926 25.5513 16.4368C24.9337 16.181 24.4058 15.7477 24.0344 15.1919C23.6629 14.6361 23.4647 13.9826 23.4647 13.3141C23.4647 12.6455 23.6629 11.992 24.0344 11.4362C24.4058 10.8804 24.9337 10.4472 25.5513 10.1913C26.1689 9.93554 26.8486 9.86863 27.5042 9.99908C28.1599 10.1295 28.7621 10.4515 29.2348 10.9242C29.8678 11.5585 30.2233 12.418 30.2233 13.3141C30.2233 14.2101 29.8678 15.0696 29.2348 15.7039V15.7039Z" />
                    <path d="M3.28309 30.9303C3.36518 30.9304 3.44647 30.9142 3.5223 30.8828C3.59813 30.8514 3.66701 30.8053 3.72496 30.7471L7.12279 27.3487C7.23877 27.2313 7.30357 27.0727 7.30305 26.9076C7.30253 26.7426 7.23673 26.5844 7.12002 26.4677C7.0033 26.351 6.84515 26.2852 6.68009 26.2847C6.51503 26.2842 6.35647 26.349 6.23902 26.4649L2.84119 29.8634C2.75381 29.9508 2.69431 30.0621 2.67021 30.1834C2.6461 30.3046 2.65848 30.4302 2.70577 30.5444C2.75307 30.6586 2.83315 30.7562 2.93591 30.8249C3.03866 30.8936 3.15948 30.9302 3.28307 30.9302L3.28309 30.9303Z" />
                    <path d="M12.6284 32.8534L9.22991 36.2519C9.17188 36.3099 9.12585 36.3788 9.09445 36.4546C9.06304 36.5304 9.04688 36.6117 9.04688 36.6938C9.04687 36.7758 9.06304 36.8571 9.09445 36.9329C9.12585 37.0088 9.17188 37.0776 9.22991 37.1357C9.28795 37.1937 9.35684 37.2397 9.43266 37.2711C9.50848 37.3026 9.58974 37.3187 9.67181 37.3187C9.75388 37.3187 9.83514 37.3026 9.91096 37.2711C9.98679 37.2397 10.0557 37.1937 10.1137 37.1357L13.5121 33.7372C13.6293 33.62 13.6952 33.4611 13.6952 33.2953C13.6952 33.1296 13.6293 32.9706 13.5121 32.8534C13.3949 32.7362 13.236 32.6704 13.0702 32.6704C12.9045 32.6704 12.7456 32.7363 12.6284 32.8535V32.8534Z" />
                    <path d="M10.3402 29.6821C10.2822 29.6241 10.2133 29.578 10.1375 29.5466C10.0617 29.5152 9.98042 29.499 9.89834 29.499C9.81627 29.499 9.735 29.5152 9.65918 29.5466C9.58336 29.578 9.51447 29.6241 9.45645 29.6821L2.70535 36.4332C2.64672 36.4911 2.60012 36.5601 2.56823 36.636C2.53634 36.712 2.51979 36.7935 2.51953 36.8759C2.51928 36.9583 2.53532 37.04 2.56673 37.1162C2.59814 37.1923 2.64431 37.2615 2.70258 37.3198C2.76084 37.3781 2.83006 37.4242 2.90623 37.4556C2.98241 37.4871 3.06404 37.5031 3.14644 37.5028C3.22884 37.5026 3.31037 37.486 3.38635 37.4541C3.46232 37.4222 3.53124 37.3756 3.58914 37.317L10.3402 30.5659C10.3983 30.5079 10.4443 30.439 10.4758 30.3632C10.5072 30.2874 10.5233 30.2061 10.5233 30.124C10.5233 30.0419 10.5072 29.9607 10.4758 29.8849C10.4443 29.809 10.3983 29.7401 10.3402 29.6821Z" />
                  </svg>
                </div>
                <h5 className="text-2xl font-semibold mb-4">Application deployment</h5>
                <p className="text-muted font-normal">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing</p>
                <Image src="/images/aboutUs/number3.png" alt="2" width="152" height="214" className="absolute top-10 right-10" />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-about-us-section-4 bg-cover bg-center">
        <div className="container mx-auto py-32 sm:px-6">
          <h2 className="text-5xl leading-tight font-semibold sm:text-4xl">Meet Our <span className="text-active">Team</span></h2>
          <div className="mt-16 flex gap-x-8 sm:gap-0 sm:flex-wrap">
            <div className="basis-1/4 sm:basis-1/2 sm:px-4">
              <div className="mb-6">
                <Image src={team1} alt="Team 1" className="w-full" />
              </div>
              <h6 className="text-2xl font-semibold text-center mb-4">Brooklyn <br className='hidden sm:block'></br>Simmons</h6>
              <p className="text-muted font-normal text-center">Co-founder, CEO</p>
            </div>
            <div className="basis-1/4 sm:basis-1/2 sm:px-4">
              <div className="mb-6">
                <Image src={team2} alt="Team 2" className="w-full" />
              </div>
              <h6 className="text-2xl font-semibold text-center mb-4">Albert <br className='hidden sm:block'></br>Flores</h6>
              <p className="text-muted font-normal text-center">Data science lead</p>
            </div>
            <div className="basis-1/4 sm:basis-1/2 sm:px-4">
              <div className="mb-6">
                <Image src={team3} alt="Team 3" className="w-full" />
              </div>
              <h6 className="text-2xl font-semibold text-center mb-4">Guy <br className='hidden sm:block'></br>Hawkins</h6>
              <p className="text-muted font-normal text-center">Data science lead</p>
            </div>
            <div className="basis-1/4 sm:basis-1/2 sm:px-4">
              <div className="mb-6">
                <Image src={team4} alt="Team 4" className="w-full" />
              </div>
              <h6 className="text-2xl font-semibold text-center mb-4">Brooklyn <br className='hidden sm:block'></br>Simmons</h6>
              <p className="text-muted font-normal text-center">Data science lead</p>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-warning">
        <div className="container mx-auto py-20 sm:px-6">
          <div className="flex sm:flex-wrap">
            <div className="basis-5/12 sm:basis-full flex justify-center sm:justify-start">
              <svg className="fill-text sm:w-[90px] sm:h-[90px]" width="180" height="180" viewBox="0 0 180 180" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g clip-path="url(#clip0_255_5875)">
                  <path d="M118.814 33.5712L121.15 34.9183C124.407 36.7996 127.283 31.7523 124.05 29.8885L121.715 28.5414C120.324 27.7386 118.549 28.2148 117.75 29.6054C116.949 30.996 117.425 32.7699 118.814 33.5712Z" />
                  <path d="M159.134 114.92V65.4169C165.247 64.0829 169.84 58.6394 169.84 52.1376C169.84 44.6385 163.734 38.5389 156.231 38.5389C152.35 38.5389 148.854 40.1777 146.371 42.7906L131.048 34.1477C129.652 33.3624 127.882 33.856 127.092 35.251C126.306 36.6474 126.798 38.4184 128.196 39.2066L143.358 47.7595C142.411 50.5292 142.384 53.5544 143.291 56.3386L100.492 81.3498C97.9934 78.3305 94.2178 76.4042 90.0008 76.4042C85.7839 76.4042 82.0082 78.3305 79.51 81.3498L36.7107 56.3386C37.6208 53.5456 37.5889 50.5103 36.6352 47.7348L79.9891 22.7279C82.48 25.4685 86.0626 27.2018 90.0502 27.2018C94.0247 27.2018 97.5942 25.4802 100.085 22.7569L111.942 29.3865C115.227 31.2126 118.034 26.1392 114.776 24.3174L103.01 17.7387C103.428 16.4323 103.659 15.0445 103.659 13.6016C103.659 6.09968 97.5536 0 90.0502 0C82.5453 0 76.4399 6.09968 76.4399 13.5987C76.4399 15.0285 76.6649 16.4061 77.0757 17.7024L33.6129 42.7718C31.1321 40.1705 27.6424 38.5389 23.771 38.5389C16.2676 38.5389 10.1621 44.6385 10.1621 52.1376C10.1621 58.6408 14.755 64.0844 20.8678 65.4169V114.92C14.755 116.254 10.1621 121.697 10.1621 128.199C10.1621 135.698 16.2676 141.799 23.771 141.799C27.7499 141.799 31.3237 140.073 33.8147 137.344L77.0757 162.298C76.6649 163.594 76.4399 164.971 76.4399 166.401C76.4399 173.9 82.5453 180 90.0502 180C97.5536 180 103.659 173.9 103.659 166.401C103.659 164.954 103.427 163.56 103.006 162.251L146.187 137.346C148.678 140.075 152.252 141.801 156.231 141.801C163.734 141.801 169.84 135.7 169.84 128.201C169.84 121.697 165.247 116.254 159.134 114.92ZM90.0502 5.80645C94.3528 5.80645 97.8526 9.30194 97.8526 13.5987C97.8526 17.8969 94.3513 21.3924 90.0502 21.3924C85.7476 21.3924 82.2463 17.8969 82.2463 13.5987C82.2463 9.30194 85.7461 5.80645 90.0502 5.80645ZM145.477 119.895L102.686 94.889C103.721 92.2181 103.877 89.2902 103.144 86.5234L146.239 61.3394C148.1 63.3556 150.553 64.8131 153.327 65.4184V114.921C150.156 115.612 147.402 117.414 145.477 119.895ZM156.231 44.3453C160.533 44.3453 164.033 47.8408 164.033 52.1376C164.033 56.4344 160.532 59.9298 156.231 59.9298C151.93 59.9298 148.428 56.4344 148.428 52.1376C148.428 47.8408 151.928 44.3453 156.231 44.3453ZM90.0008 82.2077C94.3034 82.2077 97.8032 85.7032 97.8032 90C97.8032 94.2968 94.3034 97.7923 90.0008 97.7923C85.6982 97.7923 82.1984 94.2968 82.1984 90C82.1984 85.7032 85.6982 82.2077 90.0008 82.2077ZM33.7639 61.3394L76.8594 86.5234C76.1249 89.2902 76.2816 92.2195 77.3166 94.8905L34.5245 119.895C32.6011 117.414 29.8474 115.611 26.6742 114.92V65.4169C29.4497 64.8116 31.9029 63.3542 33.7639 61.3394ZM15.9686 52.1376C15.9686 47.8408 19.4699 44.3453 23.771 44.3453C28.0721 44.3453 31.5734 47.8408 31.5734 52.1376C31.5734 56.4344 28.0721 59.9298 23.771 59.9298C19.4699 59.9298 15.9686 56.4344 15.9686 52.1376ZM23.771 135.994C19.4684 135.994 15.9686 132.499 15.9686 128.201C15.9686 123.904 19.4699 120.408 23.771 120.408C28.0721 120.408 31.5734 123.904 31.5734 128.201C31.5749 132.497 28.0736 135.994 23.771 135.994ZM36.7368 132.326C37.4771 130.008 37.5715 127.529 37.0257 125.158L80.5232 99.7403C82.3131 101.479 84.5747 102.731 87.1005 103.281L87.1455 153.12C84.3366 153.735 81.8573 155.22 79.9905 157.275L36.7368 132.326ZM90.0502 174.194C85.7476 174.194 82.2463 170.698 82.2463 166.401C82.2463 162.103 85.7476 158.608 90.0502 158.608C94.3528 158.608 97.8526 162.103 97.8526 166.401C97.8526 170.698 94.3528 174.194 90.0502 174.194ZM100.076 157.237C98.2111 155.201 95.7434 153.727 92.9505 153.119L92.9055 103.279C95.4284 102.728 97.69 101.478 99.4784 99.7389L142.976 125.157C142.43 127.529 142.525 130.008 143.265 132.326L100.076 157.237ZM156.231 135.994C151.928 135.994 148.428 132.499 148.428 128.201C148.428 123.904 151.93 120.408 156.231 120.408C160.532 120.408 164.033 123.902 164.033 128.199C164.033 132.497 160.532 135.994 156.231 135.994Z" />
                </g>
                <defs>
                  <clipPath id="clip0_255_5875">
                    <rect width="180" height="180" fill="white"/>
                  </clipPath>
                </defs>
              </svg>
            </div>
            <div className="basis-5/12 sm:basis-full">
              <h5 className="text-4xl font-bold mb-6">Join Our Team</h5>
              <p className="text-2xl font-semibold mb-8">We’re always open to meeting and chatting with talented data scientists and engineers looking to join Stratuscoder</p>
              <button
                type="button"
                className="text-lg font-semibold text-white px-10 py-3 uppercase bg-text border-2 border-text shadow-button rounded-full"
              >
                join now
              </button>
            </div>
          </div>
        </div>
      </section>
    </Fragment>
  );
}

export default AboutUs;