import { Fragment, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';

import image1 from '../public/images/careers/img1.png';
import image2 from '../public/images/careers/img2.png';

import Modal from '../components/UI/modal';

function CareersPage() {
  const [collapse, setCollapse] = useState(null);
  const [isModal, setIsModal] = useState(false);

  const toggleCollapse = (item) => {
    if (collapse !== item) {
      setCollapse(item);
    } else {
      setCollapse(null);
    }
  };

  const toggleModal = () => {
    setIsModal(!isModal);
  };

  return (
    <Fragment>
      <Head>
        <title>Careers - Stratuscoder Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <section className="bg-careers-section-1 bg-cover bg-center">
        <div className="container mx-auto pt-36 py-48">
          <div className="max-w-4xl sm:px-6">
            <p className="font-semibold uppercase mb-5 sm:text-xl">careers</p>
            <h1 className="text-6xl font-bold leading-tight mb-11 sm:text-5xl">
              Join our <span className="text-active">professional journey</span> and become the best with Statuscoder
            </h1>
            <button
              type="button"
              className="uppercase text-lg font-semibold px-14 py-3 bg-button shadow-button rounded-full">
              Join us
            </button>
          </div>
        </div>
      </section>
      <section className="bg-white">
        <div className="container mx-auto py-32">
          <div className="flex gap-x-24 sm:flex-wrap">
            <div className="basis-1/2 flex gap-x-8 sm:basis-full">
              <div className="basis-1/2">
                <Image src={image1} alt="Image 1" className="w-full" />
              </div>
              <div className="basis-1/2">
                <Image src={image2} alt="Image 2" className="w-full" />
              </div>
            </div>
            <div className="basis-1/2 sm:basis-full sm:px-6 sm:mt-16">
              <h2 className="text-5xl font-bold leading-tight mb-4 sm:3xl">
                <span className="text-active">Environment</span><br className='hidden sm:block'></br> of Innovation
              </h2>
              <p className="text-muted font-normal mb-11">Perhaps the most remunerating things about being utilized at Statuscoder is that you work with brilliant, exceptionally gifted and innovative partners who are energetic and excited. Working in this kind of climate can start motivation on each level, prompting really imaginative thoughts and improvements that can help the business contrast different rivals in the IT counseling industry.Innovate the most ideal approaches to enhance is to squeeze a thought that works somewhere else and apply it in business</p>
              <button
                type="button"
                className="uppercase text-lg font-semibold px-14 py-3 bg-button shadow-button rounded-full">
                Join us
              </button>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-careers-section-3 bg-full">
        <div className="container mx-auto py-32">
          <h2 className="text-5xl font-bold leading-tight mb-16 text-center sm:text-4xl">
            Our <span className="text-active">Culture</span>
          </h2>
          <div className="flex sm:flex-wrap sm:px-2">
            <div className="basis-overlap-1/3 sm:basis-full aspect-square rounded-full bg-careers-card backdrop-blur-lg border-2 border-card-divider p-16">
              <div className="w-20 h-20 rounded-full bg-active mx-auto flex items-center justify-center mb-6">
                <svg width="40" height="37" viewBox="0 0 40 37" fill="none" xmlns="http://www.w3.org/2000/svg" className="fill-white">
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M34.944 18.7009L30.6591 12.0703C30.327 11.5564 29.764 11.2495 29.153 11.2495H10.2478C9.63773 11.2495 9.07519 11.5556 8.74296 12.0682L4.44481 18.6997C4.00558 19.3773 4.07342 20.2719 4.60981 20.8751L18.353 36.3365C18.6932 36.7192 19.1815 36.9387 19.6929 36.9387H19.693C20.2043 36.9387 20.6927 36.7192 21.0329 36.3366L34.7777 20.8743C35.3133 20.2717 35.3817 19.378 34.944 18.7009ZM28.2834 12.791L24.6799 18.3749L21.0742 12.791H28.2834ZM16.1172 19.0234H23.2667L19.692 13.4873L16.1172 19.0234ZM18.3114 12.791L14.7156 18.3596L11.1211 12.791H18.3114ZM13.3113 19.0237L9.69824 13.4263L6.07031 19.0237H13.3113ZM6.39435 20.5651H14.1363L18.2298 33.8801L6.39435 20.5651ZM15.746 20.5651L19.6929 33.4028L23.6397 20.5651H15.746ZM21.1562 33.8808L25.2499 20.5654H32.9926L21.1562 33.8808ZM29.7035 13.4297L26.0938 19.0232H33.3181L29.7035 13.4297Z" />
                  <path d="M2.33331 19.0234H0.769231C0.344462 19.0234 0 19.3685 0 19.7943C0 20.22 0.344462 20.5651 0.769231 20.5651H2.33331C2.75808 20.5651 3.10254 20.22 3.10254 19.7943C3.10254 19.3685 2.75808 19.0234 2.33331 19.0234Z" />
                  <path d="M38.6146 19.0234H37.0505C36.6257 19.0234 36.2812 19.3685 36.2812 19.7943C36.2812 20.22 36.6257 20.5651 37.0505 20.5651H38.6146C39.0393 20.5651 39.3838 20.22 39.3838 19.7943C39.3838 19.3685 39.0393 19.0234 38.6146 19.0234Z" />
                  <path d="M33.6262 5.8449C33.3257 5.54389 32.8388 5.54389 32.5383 5.8449L29.9831 8.40538C29.6827 8.70639 29.6827 9.19448 29.9831 9.49549C30.1334 9.64603 30.3303 9.72127 30.5271 9.72127C30.724 9.72127 30.9208 9.64596 31.071 9.49549L33.6262 6.93501C33.9266 6.634 33.9266 6.14599 33.6262 5.8449Z" />
                  <path d="M9.4347 8.39178L6.87962 5.83123C6.57931 5.53022 6.09239 5.53022 5.79169 5.83123C5.49131 6.13224 5.49131 6.62033 5.79169 6.92134L8.34685 9.48182C8.49708 9.63236 8.69393 9.70759 8.89077 9.70759C9.08762 9.70759 9.28446 9.63228 9.4347 9.48182C9.73508 9.18088 9.73508 8.69271 9.4347 8.39178Z" />
                  <path d="M19.7106 0.0610352C19.2859 0.0610352 18.9414 0.406137 18.9414 0.831868V5.85524C18.9414 6.28097 19.2858 6.62607 19.7106 6.62607C20.1354 6.62607 20.4799 6.28097 20.4799 5.85524V0.831868C20.4799 0.406214 20.1354 0.0610352 19.7106 0.0610352Z" />
                  <path d="M20.2544 7.91775C20.1114 7.77437 19.9129 7.69189 19.7106 7.69189C19.5083 7.69189 19.3099 7.77437 19.1668 7.91775C19.0237 8.06112 18.9414 8.26 18.9414 8.46273C18.9414 8.66623 19.0236 8.86433 19.1668 9.00771C19.3099 9.15185 19.5083 9.23356 19.7106 9.23356C19.9129 9.23356 20.1114 9.15185 20.2544 9.00771C20.3983 8.86433 20.4799 8.66546 20.4799 8.46273C20.4799 8.26 20.3983 8.0612 20.2544 7.91775Z" />
                </svg>
              </div>
              <h6 className="text-2xl font-semibold text-center mb-4">Offsite</h6>
              <p className="text-muted text-center">We share our team’s dedication to work and try to keep the right balance between work and rest and frequently spend time together offsite to relax and enjoy a great time</p>
            </div>
            <div className="basis-overlap-1/3 sm:basis-full aspect-square -ml-11 sm:ml-0 sm:-mt-6 rounded-full bg-careers-card backdrop-blur-lg border-2 border-card-divider p-16">
              <div className="w-20 h-20 rounded-full bg-active mx-auto flex items-center justify-center mb-6">
                <svg width="40" height="37" viewBox="0 0 40 37" fill="none" xmlns="http://www.w3.org/2000/svg" className="fill-white">
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M34.944 18.7009L30.6591 12.0703C30.327 11.5564 29.764 11.2495 29.153 11.2495H10.2478C9.63773 11.2495 9.07519 11.5556 8.74296 12.0682L4.44481 18.6997C4.00558 19.3773 4.07342 20.2719 4.60981 20.8751L18.353 36.3365C18.6932 36.7192 19.1815 36.9387 19.6929 36.9387H19.693C20.2043 36.9387 20.6927 36.7192 21.0329 36.3366L34.7777 20.8743C35.3133 20.2717 35.3817 19.378 34.944 18.7009ZM28.2834 12.791L24.6799 18.3749L21.0742 12.791H28.2834ZM16.1172 19.0234H23.2667L19.692 13.4873L16.1172 19.0234ZM18.3114 12.791L14.7156 18.3596L11.1211 12.791H18.3114ZM13.3113 19.0237L9.69824 13.4263L6.07031 19.0237H13.3113ZM6.39435 20.5651H14.1363L18.2298 33.8801L6.39435 20.5651ZM15.746 20.5651L19.6929 33.4028L23.6397 20.5651H15.746ZM21.1562 33.8808L25.2499 20.5654H32.9926L21.1562 33.8808ZM29.7035 13.4297L26.0938 19.0232H33.3181L29.7035 13.4297Z" />
                  <path d="M2.33331 19.0234H0.769231C0.344462 19.0234 0 19.3685 0 19.7943C0 20.22 0.344462 20.5651 0.769231 20.5651H2.33331C2.75808 20.5651 3.10254 20.22 3.10254 19.7943C3.10254 19.3685 2.75808 19.0234 2.33331 19.0234Z" />
                  <path d="M38.6146 19.0234H37.0505C36.6257 19.0234 36.2812 19.3685 36.2812 19.7943C36.2812 20.22 36.6257 20.5651 37.0505 20.5651H38.6146C39.0393 20.5651 39.3838 20.22 39.3838 19.7943C39.3838 19.3685 39.0393 19.0234 38.6146 19.0234Z" />
                  <path d="M33.6262 5.8449C33.3257 5.54389 32.8388 5.54389 32.5383 5.8449L29.9831 8.40538C29.6827 8.70639 29.6827 9.19448 29.9831 9.49549C30.1334 9.64603 30.3303 9.72127 30.5271 9.72127C30.724 9.72127 30.9208 9.64596 31.071 9.49549L33.6262 6.93501C33.9266 6.634 33.9266 6.14599 33.6262 5.8449Z" />
                  <path d="M9.4347 8.39178L6.87962 5.83123C6.57931 5.53022 6.09239 5.53022 5.79169 5.83123C5.49131 6.13224 5.49131 6.62033 5.79169 6.92134L8.34685 9.48182C8.49708 9.63236 8.69393 9.70759 8.89077 9.70759C9.08762 9.70759 9.28446 9.63228 9.4347 9.48182C9.73508 9.18088 9.73508 8.69271 9.4347 8.39178Z" />
                  <path d="M19.7106 0.0610352C19.2859 0.0610352 18.9414 0.406137 18.9414 0.831868V5.85524C18.9414 6.28097 19.2858 6.62607 19.7106 6.62607C20.1354 6.62607 20.4799 6.28097 20.4799 5.85524V0.831868C20.4799 0.406214 20.1354 0.0610352 19.7106 0.0610352Z" />
                  <path d="M20.2544 7.91775C20.1114 7.77437 19.9129 7.69189 19.7106 7.69189C19.5083 7.69189 19.3099 7.77437 19.1668 7.91775C19.0237 8.06112 18.9414 8.26 18.9414 8.46273C18.9414 8.66623 19.0236 8.86433 19.1668 9.00771C19.3099 9.15185 19.5083 9.23356 19.7106 9.23356C19.9129 9.23356 20.1114 9.15185 20.2544 9.00771C20.3983 8.86433 20.4799 8.66546 20.4799 8.46273C20.4799 8.26 20.3983 8.0612 20.2544 7.91775Z" />
                </svg>
              </div>
              <h6 className="text-2xl font-semibold text-center mb-4">Team building</h6>
              <p className="text-muted text-center">Team spirit and common goals help to overcome any obstacles. Every member is a separate mechanism that makes a contribution to the end result. We share the same values and constantly work on becoming more efficient as a team</p>
            </div>
            <div className="basis-overlap-1/3 sm:basis-full aspect-square -ml-11 sm:ml-0 sm:-mt-6 rounded-full bg-careers-card backdrop-blur-lg border-2 border-card-divider p-16">
              <div className="w-20 h-20 rounded-full bg-active mx-auto flex items-center justify-center mb-6">
                <svg width="40" height="37" viewBox="0 0 40 37" fill="none" xmlns="http://www.w3.org/2000/svg" className="fill-white">
                  <path fill-rule="evenodd" clip-rule="evenodd" d="M34.944 18.7009L30.6591 12.0703C30.327 11.5564 29.764 11.2495 29.153 11.2495H10.2478C9.63773 11.2495 9.07519 11.5556 8.74296 12.0682L4.44481 18.6997C4.00558 19.3773 4.07342 20.2719 4.60981 20.8751L18.353 36.3365C18.6932 36.7192 19.1815 36.9387 19.6929 36.9387H19.693C20.2043 36.9387 20.6927 36.7192 21.0329 36.3366L34.7777 20.8743C35.3133 20.2717 35.3817 19.378 34.944 18.7009ZM28.2834 12.791L24.6799 18.3749L21.0742 12.791H28.2834ZM16.1172 19.0234H23.2667L19.692 13.4873L16.1172 19.0234ZM18.3114 12.791L14.7156 18.3596L11.1211 12.791H18.3114ZM13.3113 19.0237L9.69824 13.4263L6.07031 19.0237H13.3113ZM6.39435 20.5651H14.1363L18.2298 33.8801L6.39435 20.5651ZM15.746 20.5651L19.6929 33.4028L23.6397 20.5651H15.746ZM21.1562 33.8808L25.2499 20.5654H32.9926L21.1562 33.8808ZM29.7035 13.4297L26.0938 19.0232H33.3181L29.7035 13.4297Z" />
                  <path d="M2.33331 19.0234H0.769231C0.344462 19.0234 0 19.3685 0 19.7943C0 20.22 0.344462 20.5651 0.769231 20.5651H2.33331C2.75808 20.5651 3.10254 20.22 3.10254 19.7943C3.10254 19.3685 2.75808 19.0234 2.33331 19.0234Z" />
                  <path d="M38.6146 19.0234H37.0505C36.6257 19.0234 36.2812 19.3685 36.2812 19.7943C36.2812 20.22 36.6257 20.5651 37.0505 20.5651H38.6146C39.0393 20.5651 39.3838 20.22 39.3838 19.7943C39.3838 19.3685 39.0393 19.0234 38.6146 19.0234Z" />
                  <path d="M33.6262 5.8449C33.3257 5.54389 32.8388 5.54389 32.5383 5.8449L29.9831 8.40538C29.6827 8.70639 29.6827 9.19448 29.9831 9.49549C30.1334 9.64603 30.3303 9.72127 30.5271 9.72127C30.724 9.72127 30.9208 9.64596 31.071 9.49549L33.6262 6.93501C33.9266 6.634 33.9266 6.14599 33.6262 5.8449Z" />
                  <path d="M9.4347 8.39178L6.87962 5.83123C6.57931 5.53022 6.09239 5.53022 5.79169 5.83123C5.49131 6.13224 5.49131 6.62033 5.79169 6.92134L8.34685 9.48182C8.49708 9.63236 8.69393 9.70759 8.89077 9.70759C9.08762 9.70759 9.28446 9.63228 9.4347 9.48182C9.73508 9.18088 9.73508 8.69271 9.4347 8.39178Z" />
                  <path d="M19.7106 0.0610352C19.2859 0.0610352 18.9414 0.406137 18.9414 0.831868V5.85524C18.9414 6.28097 19.2858 6.62607 19.7106 6.62607C20.1354 6.62607 20.4799 6.28097 20.4799 5.85524V0.831868C20.4799 0.406214 20.1354 0.0610352 19.7106 0.0610352Z" />
                  <path d="M20.2544 7.91775C20.1114 7.77437 19.9129 7.69189 19.7106 7.69189C19.5083 7.69189 19.3099 7.77437 19.1668 7.91775C19.0237 8.06112 18.9414 8.26 18.9414 8.46273C18.9414 8.66623 19.0236 8.86433 19.1668 9.00771C19.3099 9.15185 19.5083 9.23356 19.7106 9.23356C19.9129 9.23356 20.1114 9.15185 20.2544 9.00771C20.3983 8.86433 20.4799 8.66546 20.4799 8.46273C20.4799 8.26 20.3983 8.0612 20.2544 7.91775Z" />
                </svg>
              </div>
              <h6 className="text-2xl font-semibold text-center mb-4">Knowledge sharing</h6>
              <p className="text-muted text-center">We constantly share new knowledge among team members. Statuscoder is interested in your personal and professional growth and constantly organizes knowledge-sharing events</p>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-careers-section-4 bg-cover bg-center">
        <div className="container mx-auto py-32">
          <div className="max-w-xl mx-auto">
            <h2 className="text-5xl font-bold leading-tight text-center mb-4 sm:text-4xl">
              Available <span className="text-active">Positions</span>
            </h2>
            <p className="text-muted font-semibold text-center text-2xl">We invite you to explore our open job market and apply to join our growing team</p>
          </div>
          <div className="mt-16">
            <div className="p-10 border-b-2 border-text hover:bg-services-section-2-card-hover cursor-default group">
              <div className="flex items-center justify-between sm:flex-wrap">
                <h3 className="text-4xl text-active group-hover:text-text font-bold sm:w-full sm:text-2xl sm:mb-10">Software Engineer / Node Js</h3>
                <button
                  type="button"
                  className="px-5 py-3 text-lg sm:text-basis font-semibold uppercase whitespace-nowrap border group-hover:border-button border-text drop-shadow-services-section-2-button rounded-full group-hover:bg-button group-hover:shadow-button flex items-center justify-between gap-x-1.5"
                  onClick={() => toggleCollapse(1)}
                >
                  view job
                  {collapse === 1 ? (
                    <svg width="13" height="9" viewBox="0 0 13 9" fill="none" xmlns="http://www.w3.org/2000/svg" className="stroke-text">
                      <path d="M12.1475 8L6.57377 2.09836L1 8" stroke-width="2"/>
                    </svg>
                  ) : (
                    <svg width="9" height="14" viewBox="0 0 9 14" fill="none" xmlns="http://www.w3.org/2000/svg" className="stroke-text">
                      <path d="M1 13L7 7L1 1" stroke-width="2"/>
                    </svg>
                  )}
                </button>
              </div>
              {collapse === 1 ? (
                <div className="pt-10">
                  <div className="w-3/4 sm:w-full">
                    <h6 className="text-2xl font-semibold mb-4">What you’ll be doing</h6>
                    <p className="mb-10">Analyze what the needs of the users are, then design, test, and develop software that meets those needs. Design Salesforce solutions and create effective project plans. Add value to the three stages of project work; definition, development, deployment.</p>
                    <h6 className="text-2xl font-semibold mb-6">Your tasks will include</h6>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Build Salesforce applications/frameworks using Apex, Visualforce, Lightning Component Framework (Aura and LWC) and leverage the full capabilities of the Salesforce platform to support the program</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Implement solutions that adhere to Salesforce platform best practices and perform peer code reviews</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Collaborate with Scrum Teams to estimate, plan, and manage new feature development and testing</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Work with team members to analyze business requirements, translating those requirements in to customized solutions that are highly scalable, extensible, and easy to maintain while keeping the overall end-user experience in mind</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Provide system administration support to customized applications, user permissions, security settings, custom objects, and workflow</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Assist with in-depth analysis of technical problems, suggest short- term and long-term resolutions and an overall roadmap for the completion of this process</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-10">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Support post deployment activities including knowledge transfer, process documentation and application bug fixes</p>
                    </div>
                    <h6 className="text-2xl font-semibold mb-6">What skills we’re looking for</h6>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Strong Experience developing for the Salesforce platform</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience with Salesforce API</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience creating SF objects from external file data</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience developing workflows for automated routing</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Familiarity with Salesforce specific languages Apex, SOQL, SOSL, Visualforce, LWC, Aura</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Bachelor’s degree in computer science or related field or relevant experience</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Minimum 5+ years’ experience with Hands on Salesforce Development</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Minimum 5+ years’ experience on the Salesforce Lightning Platform</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience with Agile methodologies and frameworks such as, but not limited to: SAFe, Scrum, Kanban</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Have implemented at least two or more full life cycle project in Lightning and have expert level working knowledge on major Salesforce.com technologies including Lightning web components, Apex Web Services, Visualforce, Batch Apex, Queueable Apex, etc</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experienced in web technologies such as HTML, XML, CSS, JSP and JavaScript, WSDL</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience integrating Salesforce with other applications using SOAP, REST, BULK and Streaming APIs</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience with SFDC specific IDE and version control configurations (Github, BitBucket) for Salesforce development (VS Code, IntelliJ, SFDX)</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Working knowledge and experience with complex business systems integration as well as object-oriented design patterns and development</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-16">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Provide technical assistance and end user troubleshooting for bug fixes, enhancements, and “how-to” assistance</p>
                    </div>
                    <button
                      type="button"
                      className="uppercase text-lg font-semibold px-20 py-3 bg-button shadow-button rounded-full"
                      onClick={() => setIsModal(true)}
                    >
                      apply now
                    </button>
                  </div>
                </div>
              ) : ''}
            </div>
            <div className="p-10 hover:bg-services-section-2-card-hover cursor-default group">
              <div className="flex items-center justify-between sm:flex-wrap">
                <h3 className="text-4xl text-active group-hover:text-text font-bold sm:w-full sm:text-2xl sm:mb-10">Salesforce Engineer</h3>
                <button
                  type="button"
                  className="px-5 py-3 text-lg sm:text-basis font-semibold uppercase whitespace-nowrap border group-hover:border-button border-text drop-shadow-services-section-2-button rounded-full group-hover:bg-button group-hover:shadow-button flex items-center justify-between gap-x-1.5"
                  onClick={() => toggleCollapse(2)}
                >
                  view job
                  {collapse === 2 ? (
                    <svg width="13" height="9" viewBox="0 0 13 9" fill="none" xmlns="http://www.w3.org/2000/svg" className="stroke-text">
                      <path d="M12.1475 8L6.57377 2.09836L1 8" stroke-width="2"/>
                    </svg>
                  ) : (
                    <svg width="9" height="14" viewBox="0 0 9 14" fill="none" xmlns="http://www.w3.org/2000/svg" className="stroke-text">
                      <path d="M1 13L7 7L1 1" stroke-width="2"/>
                    </svg>
                  )}
                </button>
              </div>
              {collapse === 2 ? (
                <div className="pt-10">
                  <div className="w-3/4 sm:w-full">
                    <h6 className="text-2xl font-semibold mb-4">What you’ll be doing</h6>
                    <p className="mb-10">Analyze what the needs of the users are, then design, test, and develop software that meets those needs. Design Salesforce solutions and create effective project plans. Add value to the three stages of project work; definition, development, deployment.</p>
                    <h6 className="text-2xl font-semibold mb-6">Your tasks will include</h6>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Build Salesforce applications/frameworks using Apex, Visualforce, Lightning Component Framework (Aura and LWC) and leverage the full capabilities of the Salesforce platform to support the program</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Implement solutions that adhere to Salesforce platform best practices and perform peer code reviews</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Collaborate with Scrum Teams to estimate, plan, and manage new feature development and testing</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Work with team members to analyze business requirements, translating those requirements in to customized solutions that are highly scalable, extensible, and easy to maintain while keeping the overall end-user experience in mind</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Provide system administration support to customized applications, user permissions, security settings, custom objects, and workflow</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Assist with in-depth analysis of technical problems, suggest short- term and long-term resolutions and an overall roadmap for the completion of this process</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-10">
                      <Image src="/images/careers/dot.png" alt="Dot" width="24" height="24" />
                      <p>Support post deployment activities including knowledge transfer, process documentation and application bug fixes</p>
                    </div>
                    <h6 className="text-2xl font-semibold mb-6">What skills we’re looking for</h6>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Strong Experience developing for the Salesforce platform</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience with Salesforce API</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience creating SF objects from external file data</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience developing workflows for automated routing</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Familiarity with Salesforce specific languages Apex, SOQL, SOSL, Visualforce, LWC, Aura</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Bachelor’s degree in computer science or related field or relevant experience</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Minimum 5+ years’ experience with Hands on Salesforce Development</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Minimum 5+ years’ experience on the Salesforce Lightning Platform</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience with Agile methodologies and frameworks such as, but not limited to: SAFe, Scrum, Kanban</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Have implemented at least two or more full life cycle project in Lightning and have expert level working knowledge on major Salesforce.com technologies including Lightning web components, Apex Web Services, Visualforce, Batch Apex, Queueable Apex, etc</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experienced in web technologies such as HTML, XML, CSS, JSP and JavaScript, WSDL</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience integrating Salesforce with other applications using SOAP, REST, BULK and Streaming APIs</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Experience with SFDC specific IDE and version control configurations (Github, BitBucket) for Salesforce development (VS Code, IntelliJ, SFDX)</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-4">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Working knowledge and experience with complex business systems integration as well as object-oriented design patterns and development</p>
                    </div>
                    <div className="flex gap-x-1 pl-5 items-start mb-16">
                      <Image src="/images/careers/check.png" alt="Check" width="24" height="24" />
                      <p>Provide technical assistance and end user troubleshooting for bug fixes, enhancements, and “how-to” assistance</p>
                    </div>
                    <button
                      type="button"
                      className="uppercase text-lg font-semibold px-20 py-3 bg-button shadow-button rounded-full"
                      onClick={() => setIsModal(true)}
                    >
                      apply now
                    </button>
                  </div>
                </div>
              ) : ''}
            </div>
          </div>
        </div>
      </section>
      <Modal modal={isModal} toggle={toggleModal}>
        <h3 className="text-4xl font-bold text-center mb-10">
          Available <span className="text-active">positions</span>
        </h3>
        <div className="flex gap-x-6 mb-10 sm:flex-wrap">
          <div className="basis-1/2 sm:basis-full sm:mb-10">
            <label htmlFor="name" className="font-semibold mb-3 block after:content-['*'] after:text-red-500">Name</label>
            <input type="text" id="name" className="w-full px-4 py-5 bg-input block placeholder:text-muted" placeholder="Your full name" />
          </div>
          <div className="basis-1/2 sm:basis-full">
            <label htmlFor="email" className="font-semibold mb-3 block after:content-['*'] after:text-red-500">Email</label>
            <input type="text" id="email" className="w-full px-4 py-5 bg-input block placeholder:text-muted" placeholder="Your email" />
          </div>
        </div>
        <div className="flex gap-x-6 mb-10 sm:flex-wrap">
          <div className="basis-1/2 sm:basis-full sm:mb-10">
            <label htmlFor="phone" className="font-semibold mb-3 block after:content-['*'] after:text-red-500">Phone</label>
            <input type="text" id="phone" className="w-full px-4 py-5 bg-input block placeholder:text-muted" placeholder="Your phone number" />
          </div>
          <div className="basis-1/2 sm:basis-full">
            <label htmlFor="subject" className="font-semibold mb-3 block after:content-['*'] after:text-red-500">Do you any of have the following Salesforce certifications?</label>
            <input type="text" id="subject" className="w-full px-4 py-5 bg-input block placeholder:text-muted" placeholder="Subject" />
          </div>
        </div>
        <div className="mb-10">
          <label htmlFor="message" className="font-semibold mb-3 block after:content-['*'] after:text-red-500">Submit your cover letter, resume or link to your LinkedIn profile</label>
          <textarea id="message" className="w-full px-4 py-5 bg-input block placeholder:text-muted" rows="7" placeholder="Write your message"></textarea>
        </div>
        <button
          type="button"
          className="uppercase text-lg font-semibold py-3 w-64 bg-button shadow-button rounded-full flex justify-center mx-auto"
        >
          join us
        </button>
      </Modal>
    </Fragment>
  );
}

export default CareersPage;